spring.application.name=uork

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/uork
spring.datasource.username=postgres
spring.datasource.password=admin

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Inicialização dos scripts
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:dataCategoria.sql,classpath:dataUsuario.sql
spring.jpa.defer-datasource-initialization=true