version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: uorkdb
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: uork
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: uork2026